version: '2.1'

volumes:
  kong_data: {}

networks:
  kong-net:

services:
  node-app:
    build: node-server-1/.
    ports:
      - "8080:8080/tcp"
    networks:
      - kong-net  
  kong:
    build: .
    user: root
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=kong.yml
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

